version: '3.8'

services:
  vm1:
    build: 
      context: ..
      dockerfile: environment/Dockerfile
    container_name: vm1
    volumes:
      - ..:/app
      - ../../zip/mitbih:/mitbih
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    environment:
      - VM_ID=VM1
      - DATA_PATH=/mitbih/mitbih_test.csv

  vm2:
    build: 
      context: ..
      dockerfile: environment/Dockerfile
    container_name: vm2
    volumes:
      - ..:/app
      - ../../zip/mitbih:/mitbih
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    environment:
      - VM_ID=VM2
      - DATA_PATH=/mitbih/mitbih_test.csv

  vm3:
    build: 
      context: ..
      dockerfile: environment/Dockerfile
    container_name: vm3
    volumes:
      - ..:/app
      - ../../zip/mitbih:/mitbih
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
    environment:
      - VM_ID=VM3
      - DATA_PATH=/mitbih/mitbih_test.csv

  aggregator:
    build: 
      context: ..
      dockerfile: environment/Dockerfile
    container_name: aggregator
    volumes:
      - ..:/app
    command: python /app/collective/aggregator.py
    environment:
      - SHARED_DIR=/app/results/phase5
      - MQTT_HOST=thingsboard
      - MQTT_TOKEN=AGGREGATOR_TOKEN

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard
    ports:
      - "8080:9090"
      - "1883:1883"
    environment:
      - TB_QUEUE_TYPE=in-memory
    deploy:
      resources:
        limits:
          memory: 2048M
